### ISSUE TITLE
findForFacebookOAuth method mentioned, not exists

### ISSUE THREAD

**Issue by ahmetb** [play-components/play-fbconnect#13]
When my application tries to authenticate to Facebook, code throws an `InvocationTargetException` at `FBConnect.java` and code steps into

```
[...]
}catch(InvocationTargetException e){
                throw new UnexpectedException("Module fbconnect encountered an error while calling your model's findForFacebookOAuth: "+e.getMessage());
}
```

and throws the exception. (Interestingly, `e.getMessage()` is null at this point. Maybe that InvTargetExceptn does not have a message?)

Then I found out that the method name `findForFacebookOAuth` (mentioned in exception) does not exist in the code at all (I grepped) and probably it is `facebookOAuthCallback` that you mentioned in line

```
Method method = model.getMethod("facebookOAuthCallback", new Class[] { JsonObject.class });
```

Interestingly I have a method in the User model class that I configured that matches what the plugin requires.

```
public static void facebookOAuthCallback(JsonObject data)
```

However I still get that exception. A bug?

**Comment by dhavaln** [comment]
I am facing the same issue. It works for a while and suddenly starts throwing this error.

**Comment by dhavaln** [comment]
oops. it was a code mistake.

If there is any error in the facebookOAuthCallback() method of the Model class then it throws the above error.

**Comment by ahmetb** [comment]
I switched to OAuth2 library that comes with Play 1.2+. There's exactly no need for this plugin in my opinion. Just try the sample in your samples-and-tests directory. This plugin is completely redundant.

**Comment by dhavaln** [comment]
it is working now as per my requirement but will switch anyway
