### ISSUE TITLE
Unable to get the access_token parameter from facebook graph api

### ISSUE THREAD

**Issue by sussegaduss** [play-components/play-fbconnect#4]
With the version you last pushed to master, is impossible to get the access_token parameter returned by facebook.
Here the patch i wrote in the file FBConnect.java
<code>
import com.google.gson.JsonPrimitive;
JsonObject jsonData = WS.url(uri).get().getJson().getAsJsonObject();
jsonData.add("accessToken", new JsonPrimitive(accessToken));
</code>

and thats it!!!! now i have access to allData from the user authenticated.!!

I hope you include this on your project. Its very simple and we get so much!!

**Comment by mmurray** [comment]
Thanks I'll add this today.

**Comment by mmurray** [comment]
Finally added this, thanks for the suggestion. It'll be in 0.4 which I'm pushing to the play module repo tonight.

https://github.com/murz/play-fbconnect/commit/18b8881d2bce3803c242ac0a71f322e88b52bb69
